### ISSUE TITLE
Workspaces don't show up in workspace list if extra tags added

### ISSUE THREAD

**Issue by jderieg** [AzBuilder/terrakube#473]
### Bug description 🐞

If you have a cloud block using tags to find the workspace in Terrakube, similar to the following:

```
terraform {
  cloud {
    organization = "my-org"
    hostname     = "terrakube-api.example.com"
    workspaces {
      tags = ["iam"]
    }
  }
}
```

Terraform is only able to find the workspace in Terrakube if _only_ the `iam` tag exists. If there are any additional tags added for sorting or other purposes in Terrakube, Terraform fails to discover the workspace, even though it has a tag matching the cloud block.

### Steps to reproduce

Works with the above cloud block if the tag matches exactly:
![works](https://github.com/AzBuilder/terrakube/assets/63372114/8c19e026-4957-43fd-b3fa-3a2da4b83247)

If you add a second tag, Terraform fails to find the workspace, even though it has a tag that matches the configuration in the cloud-block:
![nowork](https://github.com/AzBuilder/terrakube/assets/63372114/b2c45959-b14d-429b-8cce-0d74240753da)

### Expected behavior

Terrakube should allow Terraform to match on individual tags and ignore any other tags that might be present on a workspace.

**Comment by alfespa17** [comment]
If I remembered correctly right now to find a particular workspaces all tags should match

But what should happen if for example you have multiple tags?

```terraform
terraform {
  cloud {
    organization = "my-org"
    hostname     = "terrakube-api.example.com"
    workspaces {
      tags = ["iam", "test"]
    }
  }
}
```

**Comment by jderieg** [comment]
Yes, if I have 2 tags in the cloud-block the workspace needs to have both tags to match (but it shouldn't matter if it has additional ones).

**Comment by jderieg** [comment]
In a related error, if I try to use the same tag on many workspaces (which I should be able to do... it's the whole point of using tags), I start getting this error randomly in the api, although sometimes it works and doesn't throw the error:

```2023-08-18 19:08:04.026 ERROR 1 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: javax.persistence.RollbackException: Error while committing the transaction] with root cause

org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "const_tag_org"
  Detail: Key (organization_id, name)=(c0842cc6-3f3b-401f-8f49-e9a5859ca282, test) already exists.```

**Comment by alfespa17** [comment]
> const_tag_org

I added that constraint "const_tag_org "for tags logic recently, the tag name should be unique inside a organization, could you show a little more of the logs so I can see where the code is trying to add a duplicated value so I can check the validations. 

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/resources/db/changelog/local/changelog-2.15.0-tags-constraint.xml#L12

**Comment by alfespa17** [comment]
> Yes, if I have 2 tags in the cloud-block the workspace needs to have both tags to match (but it shouldn't matter if it has additional ones).

Yeah in that case I will have to change the logic a little bit, thank you for your feedback

**Comment by jderieg** [comment]
Yeah, here's the rest of that log:
```
2023-08-18 19:08:04.026 ERROR 1 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] threw exception

org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "const_tag_org"
  Detail: Key (organization_id, name)=(c0842cc6-3f3b-401f-8f49-e9a5859ca282, test) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:316) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:879) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:901) ~[postgresql-42.4.3.jar:42.4.3]
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.commit(AbstractLogicalConnectionImplementor.java:86) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:282) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at com.yahoo.elide.datastores.jpa.transaction.NonJtaTransaction.commit(NonJtaTransaction.java:64) ~[elide-datastore-jpa-6.1.12.jar:na]
	at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.commit(InMemoryStoreTransaction.java:196) ~[elide-core-6.1.12.jar:na]
	at com.yahoo.elide.Elide.handleRequest(Elide.java:528) ~[elide-core-6.1.12.jar:na]
	at com.yahoo.elide.Elide.post(Elide.java:319) ~[elide-core-6.1.12.jar:na]
	at com.yahoo.elide.spring.controllers.JsonApiController$2.call(JsonApiController.java:113) ~[elide-spring-boot-autoconfigure-6.1.12.jar:na]
	at com.yahoo.elide.spring.controllers.JsonApiController$2.call(JsonApiController.java:110) ~[elide-spring-boot-autoconfigure-6.1.12.jar:na]
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:337) ~[spring-web-5.3.28.jar:5.3.28]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by alfespa17** [comment]
I fixed the logic when searching tags, I will try to see if I can fix the database issue before releasing a hotfix version 2.15.1

**Comment by jderieg** [comment]
one more db issue, not sure if you want me to create another bug report for this, or just wrap it up in this one:

If a workspace was created, and then deleted, Terrakube won't allow creation of the workspace again with the same name (e.g. if the workspace was deleted on accident). It throws a duplicate-key error saying that the workspace already exists, even though the Terrakube UI doesn't see it.

```
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "const_workspace"
  Detail: Key (organization_id, name)=(c0842cc6-1f3b-401f-4f49-e9a5659ca282, rds-serverless) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:316) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:879) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:901) ~[postgresql-42.4.3.jar:42.4.3]
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.commit(AbstractLogicalConnectionImplementor.java:86) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:282) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at com.yahoo.elide.datastores.jpa.transaction.NonJtaTransaction.commit(NonJtaTransaction.java:64) ~[elide-datastore-jpa-6.1.12.jar:na]
	at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.commit(InMemoryStoreTransaction.java:196) ~[elide-core-6.1.12.jar:na]
	at com.yahoo.elide.Elide.handleRequest(Elide.java:528) ~[elide-core-6.1.12.jar:na]
	at com.yahoo.elide.Elide.post(Elide.java:319) ~[elide-core-6.1.12.jar:na]
	at com.yahoo.elide.spring.controllers.JsonApiController$2.call(JsonApiController.java:113) ~[elide-spring-boot-autoconfigure-6.1.12.jar:na]
	at com.yahoo.elide.spring.controllers.JsonApiController$2.call(JsonApiController.java:110) ~[elide-spring-boot-autoconfigure-6.1.12.jar:na]
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:337) ~[spring-web-5.3.28.jar:5.3.28]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2023-08-21T20:48:53.505387506Z
```

**Comment by alfespa17** [comment]
> one more db issue, not sure if you want me to create another bug report for this, or just wrap it up in this one:
> 
> If a workspace was created, and then deleted, Terrakube won't allow creation of the workspace again with the same name (e.g. if the workspace was deleted on accident). It throws a duplicate-key error saying that the workspace already exists, even though the Terrakube UI doesn't see it.
> 
> ```
> org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "const_workspace"
>   Detail: Key (organization_id, name)=(c0842cc6-1f3b-401f-4f49-e9a5659ca282, rds-serverless) already exists.
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[postgresql-42.4.3.jar:42.4.3]
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[postgresql-42.4.3.jar:42.4.3]
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[postgresql-42.4.3.jar:42.4.3]
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:316) ~[postgresql-42.4.3.jar:42.4.3]
> 	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:879) ~[postgresql-42.4.3.jar:42.4.3]
> 	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:901) ~[postgresql-42.4.3.jar:42.4.3]
> 	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.commit(AbstractLogicalConnectionImplementor.java:86) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
> 	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:282) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
> 	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
> 	at com.yahoo.elide.datastores.jpa.transaction.NonJtaTransaction.commit(NonJtaTransaction.java:64) ~[elide-datastore-jpa-6.1.12.jar:na]
> 	at com.yahoo.elide.core.datastore.inmemory.InMemoryStoreTransaction.commit(InMemoryStoreTransaction.java:196) ~[elide-core-6.1.12.jar:na]
> 	at com.yahoo.elide.Elide.handleRequest(Elide.java:528) ~[elide-core-6.1.12.jar:na]
> 	at com.yahoo.elide.Elide.post(Elide.java:319) ~[elide-core-6.1.12.jar:na]
> 	at com.yahoo.elide.spring.controllers.JsonApiController$2.call(JsonApiController.java:113) ~[elide-spring-boot-autoconfigure-6.1.12.jar:na]
> 	at com.yahoo.elide.spring.controllers.JsonApiController$2.call(JsonApiController.java:110) ~[elide-spring-boot-autoconfigure-6.1.12.jar:na]
> 	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:337) ~[spring-web-5.3.28.jar:5.3.28]
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
> 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
> 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
> 2023-08-21T20:48:53.505387506Z
> ```

This is working as expected there is a unique a constraint in the database for the workspace name inside an organization because when you delete a workspace we use a "soft delete" for auditing purposes. 

What we usually do is just add some three of four character random suffix so the name is never duplicated.

**Comment by alfespa17** [comment]
You could check 2.15.1, I fixed the issue to search workspaces and I refactored the code for the database issue for the tags (I was not able to reproduce it but I change the logic so it won't break)

**Comment by jderieg** [comment]
2.15.1 fixed the issue: if I have a workspace with an extra tag (that the cloud-block doesn't list) it still shows up in the `terraform workspace list` even if there's an extra tag associated with the workspace. Thanks!

It still throws an error if you type in a tag that already exists in the DB. If you select it from the dropdown list instead, it doesn't throw the error.

**Comment by alfespa17** [comment]
Now I get it, your are talking about this dropdown
![image](https://github.com/AzBuilder/terrakube/assets/4461895/131d464e-8dce-4352-b9b0-5aa6231a9e2f)

**Comment by alfespa17** [comment]
Try version 2.15.2

I sent #480 to fix the issue in the UI when adding tags.

**Comment by jderieg** [comment]
Yes! This fixed the issue. Thanks so much!
I tested typing in a tag in a workspace that already existed. It used the one that already existed in the DB (and in the dropdown list) successfully without throwing an error.
