### ISSUE TITLE
Getting a blank page when clicking into a workspace in the UI

### ISSUE THREAD

**Issue by jderieg** [AzBuilder/terrakube#564]
### Bug description 🐞

Testing out version 2.17.0-beta.4. I can log in just fine and see all my workspaces, but when I click into any one of them, I get a blank page. The browser console shows the following:
![2023-10-30_16-17](https://github.com/AzBuilder/terrakube/assets/63372114/74396642-211c-473d-80c8-07c65bd2682a)

I tested this in multiple browsers with the same result.

### Steps to reproduce

click into any workspace on version 2.17.0-beta.4

### Expected behavior

should load the workspace settings

**Comment by jderieg** [comment]
I also tried creating a new workspace to make sure it wasn't an issue with pre-existing workspaces. Same issue on the new one.

**Comment by jcanizalez** [comment]
Thanks @jderieg  I fixed the issue that was appearing in the cli based workspaces

**Comment by jderieg** [comment]
Thank you @jcanizalez!

**Comment by jderieg** [comment]
Still seeing some issues in workspaces on the new version (2.17.0-beta.5). I can click into the workspace now, but viewing the diagram and code for a state:
![2023-10-31_13-59](https://github.com/AzBuilder/terrakube/assets/63372114/352458da-6861-4f2a-aedf-bcbd611456c6)

**Comment by jderieg** [comment]
ah, this might be a problem on our end... I changed the URL of our terrakube app and the api might still be pointing to the old location. I'll do some more digging.

**Comment by jderieg** [comment]
I may have to do some db record updates. It seems that every workspace that was created prior to me changing the URL has the old URL tied to it.

**Comment by jderieg** [comment]
OK, I'm having some trouble figuring something out.
We changed the URL of our terrakube. For example's sake, let's say I changed it from terrakube-api.example.com to terrakube-api.test.tech.
Everything works fine, except if there is a workspace where a state file exists from _before_ the URL change, my browser throws an error because it's trying to use the _old_ .com URL instead of the new one.
I was thinking this was probably a URL that got written to a db record for the job or something, but I can't find anything in my DB that would be holding on to that old URL.
Here's a screenshot of the problem:
![2023-11-01_10-14](https://github.com/AzBuilder/terrakube/assets/63372114/941fc68a-d42a-43c1-9de1-98c737170453)

Any ideas?

**Comment by alfespa17** [comment]
Hello @jderieg.

There is one table call "history" there is one field called "output", that field should have the old URL.

Could you check that field?

**Comment by jderieg** [comment]
Yes! I think that's it. Thanks @alfespa17 . Not sure how I missed that, I thought I had checked there. I'll get that changed and test again.

**Comment by alfespa17** [comment]
There is also a table call "step" that will have a field call "output" that will require to update the URL

**Comment by jderieg** [comment]
Perfect! Everything seems to be working as expected now.

**Comment by jderieg** [comment]
Sorry guys, getting another error:
```
org.postgresql.util.PSQLException: ERROR: column "serial" is of type integer but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 177
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152) ~[postgresql-42.4.3.jar:42.4.3]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3375) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3937) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:107) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
```

That's what's in the api pod log. Terraform is throwing an error that it can't connect to terrakube.

```
There was an error connecting to Terraform Cloud. Please do not exit
Terraform to prevent data loss! Trying to restore the connection...

Still trying to restore the connection... (4s elapsed)
Still trying to restore the connection... (7s elapsed)
Still trying to restore the connection... (11s elapsed)
Still trying to restore the connection... (15s elapsed)
Still trying to restore the connection... (20s elapsed)
```

**Comment by alfespa17** [comment]
I am aware of that issue, I created a beta a few minutes ago which I expect will be the final fix for that

https://github.com/AzBuilder/terrakube/releases/tag/2.17.0-beta.8

**Comment by jderieg** [comment]
ah, ok. I'll upgrade and test again

**Comment by jderieg** [comment]
Yeah, that latest beta fixed the connection/sql issue.
Getting this error on one of the states I tried to push:
```
Failed to persist state: unsupported attribute "override_json"
```
I think we've seen that error before, but I'm not sure what we did to fix that.

**Comment by alfespa17** [comment]
Hello @jderieg 
Can you give an example of the commands and terraform version?

**Comment by jderieg** [comment]
I figured that one out. The source state hadn't been updated for several Terraform versions. I updated it on terraform.io, re-pulled it, and pushed it to terrakube and it worked.

Should this 'Resources' be greater than 0 if there is a state file with resources in it?
![2023-11-01_14-30](https://github.com/AzBuilder/terrakube/assets/63372114/215fd45f-b1ae-4967-83e5-c1cd76ba45ed)

**Comment by alfespa17** [comment]
I think is not counting the resources for child modules, I open a new issue for that

https://github.com/AzBuilder/terrakube/issues/571

**Comment by jderieg** [comment]
Thanks @alfespa17 
Sorry for all the extra noise on this one guys. I see a lot of potential in this product and want it to be as awesome as possible! We're still not using it in production yet, but likely will be after this 2.17.0 release! Thanks for being so responsive. Terrakube is an amazing product!

**Comment by jcanizalez** [comment]
Thank you for your feedback, @jderieg. We appreciate your support in testing the beta versions and providing us with feedback

**Comment by alfespa17** [comment]
Thanks for your feedback @jderieg and thank you for testing several features over the past weeks.

We really appreciate your feedback I think it help us a lot to improve some missing parts in the UI and features in the backend.

I am glad you like Terakube.
